/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */

/*
 * GUI.java Created on 04.10.2012, 12:04:56
 */
package project.view;


/**
 * @author Danish
 */
public class GUIEXPERIMENTAL extends javax.swing.JFrame
{

    /** Creates new form GUI */
    public GUIEXPERIMENTAL()
    {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked" , "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents()
    {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        primeContainer = new javax.swing.JPanel();
        verfahrenLabel = new javax.swing.JLabel();
        verfahrenAsuwahl = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler( new java.awt.Dimension( 0, 0 ),
                new java.awt.Dimension( 0, 0 ), new java.awt.Dimension( 32767,
                        0 ) );
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton1.setText( "jButton1" );

        jLabel2.setText( "jLabel2" );

        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

        jTabbedPane1.setToolTipText( "Primzahlent" );
        jTabbedPane1.setName( "Primzahlen" ); // NOI18N

        verfahrenLabel.setText( "jLabel1" );

        verfahrenAsuwahl.setModel( new javax.swing.DefaultComboBoxModel(
                new String[] { "Sieb" , "Brute-Force" } ) );
        verfahrenAsuwahl.addActionListener( new java.awt.event.ActionListener()
        {

            public void actionPerformed(java.awt.event.ActionEvent evt)
            {

                verfahrenAsuwahlActionPerformed( evt );
            }
        } );

        output.setColumns( 20 );
        output.setRows( 5 );
        jScrollPane2.setViewportView( output );

        jTextField1.setText( "Max" );

        jLabel1.setText( "Primzahlen bis " );

        javax.swing.GroupLayout primeContainerLayout = new javax.swing.GroupLayout(
                primeContainer );
        primeContainer.setLayout( primeContainerLayout );
        primeContainerLayout
                .setHorizontalGroup( primeContainerLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup(
                                primeContainerLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                primeContainerLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING )
                                                        .addGroup(
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                14,
                                                                                14,
                                                                                14 )
                                                                        .addComponent(
                                                                                verfahrenLabel,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                46,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                        .addComponent(
                                                                                verfahrenAsuwahl,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                        .addGroup(
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addContainerGap()
                                                                        .addComponent(
                                                                                jSeparator1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                357,
                                                                                Short.MAX_VALUE ) ) )
                                        .addGap( 19, 19, 19 ) )
                        .addGroup(
                                primeContainerLayout
                                        .createSequentialGroup()
                                        .addGroup(
                                                primeContainerLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false )
                                                        .addGroup(
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addContainerGap(
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE )
                                                                        .addComponent(
                                                                                jLabel1 )
                                                                        .addGap(
                                                                                18,
                                                                                18,
                                                                                18 )
                                                                        .addComponent(
                                                                                jTextField1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                92,
                                                                                92,
                                                                                92 )
                                                                        .addComponent(
                                                                                filler1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE ) ) )
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                86, Short.MAX_VALUE )
                                        .addComponent(
                                                jScrollPane2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addContainerGap() )
                        .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                primeContainerLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                jProgressBar1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                366, Short.MAX_VALUE )
                                        .addContainerGap() ) );
        primeContainerLayout
                .setVerticalGroup( primeContainerLayout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING )
                        .addGroup(
                                primeContainerLayout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                primeContainerLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE )
                                                        .addComponent(
                                                                verfahrenLabel,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                23,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                                        .addComponent(
                                                                verfahrenAsuwahl,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE ) )
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                        .addComponent(
                                                jSeparator1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                7,
                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                        .addGroup(
                                                primeContainerLayout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING )
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                                                        .addComponent(
                                                                                jScrollPane2,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                177,
                                                                                Short.MAX_VALUE ) )
                                                        .addGroup(
                                                                primeContainerLayout
                                                                        .createSequentialGroup()
                                                                        .addGap(
                                                                                14,
                                                                                14,
                                                                                14 )
                                                                        .addGroup(
                                                                                primeContainerLayout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.BASELINE )
                                                                                        .addComponent(
                                                                                                jTextField1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                                        .addComponent(
                                                                                                jLabel1 ) )
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                99,
                                                                                Short.MAX_VALUE )
                                                                        .addComponent(
                                                                                filler1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE )
                                                                        .addGap(
                                                                                50,
                                                                                50,
                                                                                50 ) ) )
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                        .addComponent(
                                                jProgressBar1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE ) ) );

        jTabbedPane1.addTab( "Primzahlen", primeContainer );

        jTextArea1.setColumns( 20 );
        jTextArea1.setRows( 5 );
        jTextArea1.setText( "Hilfe -Bereich" );
        jScrollPane1.setViewportView( jTextArea1 );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup( layout
                .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                .addGroup(
                        javax.swing.GroupLayout.Alignment.TRAILING,
                        layout.createSequentialGroup()
                                .addComponent( jTabbedPane1,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        391, Short.MAX_VALUE )
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                .addComponent( jScrollPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        126,
                                        javax.swing.GroupLayout.PREFERRED_SIZE )
                                .addContainerGap() ) );
        layout.setVerticalGroup( layout
                .createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.LEADING )
                                                .addComponent(
                                                        jTabbedPane1,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        278, Short.MAX_VALUE )
                                                .addComponent(
                                                        jScrollPane1,
                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        278, Short.MAX_VALUE ) )
                                .addContainerGap() ) );

        pack();
    }// </editor-fold>

    private void verfahrenAsuwahlActionPerformed(java.awt.event.ActionEvent evt)
    {

        System.out
                .println( evt
                        + " in private void verfahrenAsuwahlActionPerformed(java.awt.event.ActionEvent evt) " );
    }

    /**
     * @param args
     *            the command line arguments
     */
    public static void main(String args[])
    {

        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed"
        // desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase
         * /tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels() )
            {
                if ( "Nimbus".equals( info.getName() ) )
                {
                    javax.swing.UIManager.setLookAndFeel( info.getClassName() );
                    break;
                }
            }
        }
        catch ( ClassNotFoundException ex )
        {
            java.util.logging.Logger.getLogger( GUIEXPERIMENTAL.class.getName() ).log(
                    java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( InstantiationException ex )
        {
            java.util.logging.Logger.getLogger( GUIEXPERIMENTAL.class.getName() ).log(
                    java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( IllegalAccessException ex )
        {
            java.util.logging.Logger.getLogger( GUIEXPERIMENTAL.class.getName() ).log(
                    java.util.logging.Level.SEVERE, null, ex );
        }
        catch ( javax.swing.UnsupportedLookAndFeelException ex )
        {
            java.util.logging.Logger.getLogger( GUIEXPERIMENTAL.class.getName() ).log(
                    java.util.logging.Level.SEVERE, null, ex );
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater( new Runnable()
        {

            public void run()
            {

                new GUIEXPERIMENTAL().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea output;
    private javax.swing.JPanel primeContainer;
    private javax.swing.JComboBox verfahrenAsuwahl;
    private javax.swing.JLabel verfahrenLabel;
    // End of variables declaration
}
